services:
  api:
    build: .
    container_name: task_api
    restart: unless-stopped
    ports:
      - "0.0.0.0:${APP_PORT}:8000"
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_PORT: "8000"
      TEABLE_BASE_URL: ${TEABLE_BASE_URL}
      TEABLE_API_TOKEN: ${TEABLE_API_TOKEN}
      TEABLE_TABLE_TASKS: ${TEABLE_TABLE_TASKS}
      TEABLE_TABLE_TEAM: ${TEABLE_TABLE_TEAM}
      TEABLE_TABLE_PROJECTS: ${TEABLE_TABLE_PROJECTS}
      TEABLE_TABLE_CLIENTES: ${TEABLE_TABLE_CLIENTES}
      AUTH_USERNAME: ${AUTH_USERNAME}
      AUTH_PASSWORD: ${AUTH_PASSWORD}
      AUTH_SECRET_KEY: ${AUTH_SECRET_KEY}
