TASK_PRIORITIES = ["BAJA", "MEDIA", "ALTA", "CRÍTICA"]
TASK_STATUSES = [
    "PENDIENTE",
    "EN_PROGRESO",
    "EN_REVISION",
    "BLOQUEADA",
    "COMPLETADA",
    "CANCELADA",
]
TASK_TYPES = [
    "OPERATIVA",
    "TECNICA",
    "ESTRATEGICA",
    "CONTENIDO",
    "SOPORTE",
    "PERSONAL",
]

TEAM_MEMBER_TYPES = ["HUMANO", "AGENTE_IA", "EXTERNO"]
TEAM_MEMBER_STATUSES = ["ACTIVO", "INACTIVO"]

PROJECT_TYPES = [
    "CLIENTE",
    "INTERNO",
    "AUTOMATIZACION",
    "CONTENIDO",
    "INFRAESTRUCTURA",
    "PRODUCTO",
]
PROJECT_STATUSES = ["ACTIVO", "PAUSADO", "CERRADO", "CANCELADO"]
PROJECT_PRIORITIES = ["BAJA", "MEDIA", "ALTA", "CRÍTICA"]
